### ISSUE TITLE
PCIe links down on soft-reboot

### ISSUE THREAD

**Issue by pks** [MarvellEmbeddedProcessors/linux-marvell#1]
I'm trying to use a Ubiquiti mini PCIe SR71-E card with a SolidRun ClearFog-A1/PRO (Rev 2.1).
The card works fine, and is correctly recognized:`
01:00.0 Network controller: Qualcomm Atheros AR928X Wireless Network Adapter (PCI-Express) (rev 01)`.

But the card is not recognized anymore after a soft-reboot, e.g. after calling `reboot`.
The card works again if the board is first powered down and then booted again.

I'm using the SolidRun's official Debian  image ([sr-a38x-debian-jessie-20160703](http://images.solid-build.xyz/A38X/)):
`Linux clearfog 3.10.70-marvell-clearfog #3 SMP Sun Jul 10 21:43:27 UTC 2016 armv7l GNU/Linux`.

I can rule out the card's driver (ath9k) as they are not included in the image.

`dmesg` from proper boot:
`[    1.110828] mvebu-pcie pcie-controller.3: PCIe1.0: link up`
`[    1.110847] mvebu-pcie pcie-controller.3: PCIe2.0: link down`
`[    1.110960] mvebu-pcie pcie-controller.3: PCI host bridge to bus 0000:00`
`[    1.110967] pci_bus 0000:00: root bus resource [io  0x1000-0xfffff]`
`[    1.110970] pci_bus 0000:00: root bus resource [mem 0xe0000000-0xe7ffffff]`
`[    1.110974] pci_bus 0000:00: root bus resource [bus 00-ff]`
`[    1.110988] pci 0000:00:02.0: [11ab:7846] type 01 class 0x060400`
`[    1.111102] pci 0000:00:03.0: [11ab:7846] type 01 class 0x060400`
`[    1.111208] pci 0000:00:02.0: bridge configuration invalid ([bus 00-00]), reconfiguring`
`[    1.111213] pci 0000:00:03.0: bridge configuration invalid ([bus 00-00]), reconfiguring`
`[    1.111307] pci 0000:01:00.0: [168c:002a] type 00 class 0x028000`
`[    1.111323] pci 0000:01:00.0: reg 10: [mem 0x42000000-0x4200ffff 64bit]`
`[    1.111395] pci 0000:01:00.0: supports D1`
`[    1.111398] pci 0000:01:00.0: PME# supported from D0 D1 D3hot`
`[    1.111511] pci_bus 0000:01: busn_res: [bus 01-ff] end is updated to 01`
`[    1.111587] pci_bus 0000:02: busn_res: [bus 02-ff] end is updated to 02`
`[    1.111620] pci 0000:00:02.0: BAR 8: assigned [mem 0xe0000000-0xe00fffff]`
`[    1.111625] pci 0000:01:00.0: BAR 0: assigned [mem 0xe0000000-0xe000ffff 64bit]`
`[    1.111634] pci 0000:00:02.0: PCI bridge to [bus 01]`
`[    1.111638] pci 0000:00:02.0:   bridge window [mem 0xe0000000-0xe00fffff]`
`[    1.111646] pci 0000:00:03.0: PCI bridge to [bus 02]`
`[    2.260169] ehci-pci: EHCI PCI platform driver`

`dmesg` after reboot:
`[    1.110714] mvebu-pcie pcie-controller.3: PCIe1.0: link down`
`[    1.110731] mvebu-pcie pcie-controller.3: PCIe2.0: link down`
`[    1.110828] mvebu-pcie pcie-controller.3: PCI host bridge to bus 0000:00`
`[    1.110834] pci_bus 0000:00: root bus resource [io  0x1000-0xfffff]`
`[    1.110838] pci_bus 0000:00: root bus resource [mem 0xe0000000-0xe7ffffff]`
`[    1.110842] pci_bus 0000:00: root bus resource [bus 00-ff]`
`[    1.110855] pci 0000:00:02.0: [11ab:7846] type 01 class 0x060400`
`[    1.110955] pci 0000:00:03.0: [11ab:7846] type 01 class 0x060400`
`[    1.111048] pci 0000:00:02.0: bridge configuration invalid ([bus 00-00]), reconfiguring`
`[    1.111052] pci 0000:00:03.0: bridge configuration invalid ([bus 00-00]), reconfiguring`
`[    1.111140] pci_bus 0000:01: busn_res: [bus 01-ff] end is updated to 01`
`[    1.111215] pci_bus 0000:02: busn_res: [bus 02-ff] end is updated to 02`
`[    1.111232] pci 0000:00:02.0: PCI bridge to [bus 01]`
`[    1.111238] pci 0000:00:03.0: PCI bridge to [bus 02]`
`[    2.242095] ehci-pci: EHCI PCI platform driver`

**Comment by wujingbang** [comment]
i am facing the same problem now with AR9462 using linux4.4 but different Soc.
It seems like a software problem or a memory mapping issue .. 
Have you solved this problem??

**Comment by pks** [comment]
No, couldn't get it to work -- had to get rid of the device, as the manufacturer (SolidRun) also couldn't provide a solution.

**Comment by wujingbang** [comment]
i have figure it out, it's a hardware initialization problem. The connection of the "perst" of the wifi card is wrongly connected or configured
