### ISSUE TITLE
Armada-xp-linksys-mamba

### ISSUE THREAD

**Issue by nitroshift** [MarvellEmbeddedProcessors/linux-marvell#2]
The .dts file for the Linksys WRT1900AC v1 (Mamba) is missing. It is based on the Armada XP SoC and it has 256Mb of RAM. Building with the default profile results in an unbootable image since it selects armada-xp-db.dts which includes the armada-xp-mv78460.dtsi instead of armada-xp-mv78230.dtsi. Also, armada-xp-db.dts defines 2Gb of RAM. Please create a profile for the above-mentioned device that includes all necessary requirements to build a working image. Thank you.

**Comment by nitroshift** [comment]
Nevermind, patched the tree myself.

**Comment by smurfix** [comment]
You might have attached a patch, you know …
